inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

# Always add the frozen string literal magic comment to the top of files
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always
